Code cleanup, tooltips in grid view and close button background the same as navbar
EbbDrop/SmarterSmartchool pull request #6
Opened 2022-11-30 20:18 UTC by Iliannnn

- Added tooltips when hovering over a result in grid view
- Made the background color of the close button in the grid view the same as Smartschool's navbar (also works with custom and dark theme)
- Code cleanup

2022-11-30 20:57 UTC, EbbDrop requested changes
Thank you for making this. I definitely want to merge the pop ups but I'm not sure about the color changes. Could you split those into a separate PR.

There also seems to be a problem with the disclaimer:
![Screenshot_2022-11-30_21-52-37](https://user-images.githubusercontent.com/5936614/204905751-3863af2e-f70a-4fe9-bfab-a4127cf2a26c.png)

2022-11-30 20:57 UTC, EbbDrop commented on BetterResults.js
> +}
Can you change these to `rem` instead of `px` units. You also left a second margin-left at the top.

2022-12-02 18:41 UTC, Iliannnn commented
> Thank you for making this. I definitely want to merge the pop ups but I'm not sure about the color changes. Could you split those into a separate PR.
> 
> There also seems to be a problem with the disclaimer: ![Screenshot_2022-11-30_21-52-37](https://user-images.githubusercontent.com/5936614/204905751-3863af2e-f70a-4fe9-bfab-a4127cf2a26c.png)

![jGWqP2](https://user-images.githubusercontent.com/72648901/205363462-ef9a6d23-a605-4cc4-97c2-a9f0370fde9f.png)
Fixed that now. Will split the features now.

2022-12-02 20:23 UTC, EbbDrop requested changes
Just forgot to update the change log. This looks good to merge after that

2022-12-02 20:23 UTC, EbbDrop commented on Changelog.txt
> +- Code cleanup
```suggestion
- Added tooltips when hovering over a result in grid view
- Code cleanup
```

You forgot to remove this

2022-12-03 10:35 UTC, Iliannnn commented
> Just forgot to update the change log. This looks good to merge after that

Updated

2022-12-03 10:56 UTC, merged

2022-12-03 11:04 UTC, EbbDrop commented
Thanks for the update. It will take a few days before google approves and pushes the updates to everybody.